### ISSUE TITLE
MongoError: QueryFailure flag set on getmore command

### ISSUE THREAD

**Issue by gaggle** [Automattic/monk#107]
When I run a find, ala:

    var opts = {
      limit: limit || 0,
      sort: sort || {}
    }
    db.get(collection).find("foo", opts, function (err, result) {
        console.log(err, result)
    })

My server responds with this error after a few seconds:

    MongoError: QueryFailure flag set on getmore command
    at Object.toError (/home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:853:31
    at /home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null. (/home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at EventEmitter.emit (events.js:95:17)
    at null. (/home/ubuntu/volume/<module>@2015-09-16T17-43-53.965Z/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at EventEmitter.emit (events.js:98:17)

I'm not sure what's going on... I guess something goes wrong when it returns a batch?

There is a [Mongo driver changelog](http://mongodb.github.io/node-mongodb-native/1.4/changelog/changelog.html#id48) that makes a reference that sounds superficially related, but I really have no clue. Does this sound `monk` related or something elsewhere in my stack?

**Comment by geekraver** [comment]
I have this issue too. Seems you can't combine sort and limit. Looking at the activity graph this project looks kind of dead so it may be time to move on. Looks like mongoose is getting all the love.

**Comment by bhs128** [comment]
I had the same issue. I was able to fix it by creating an index on the collection. I assume it is related to this:

https://docs.mongodb.org/v3.0/reference/limits/#Sort-Operations

>Sort Operations
>If MongoDB cannot use an index to get documents in the requested sort order, the combined size of all documents in the sort operation, plus a small overhead, must be less than 32 megabytes.

**Comment by renatossilva** [comment]
Hi bhs128,

I had the same problem and resolved it by creating an extra index too. 
Thanks
