### ISSUE TITLE
TypeError: Cannot read property 'ops' of null

### ISSUE THREAD

**Issue by neil-s** [Automattic/monk#137]
Just started a fresh file to isolate the issue:

```js
var url =  "mongodb://username:password@server.mlab.com:19664/databasename";
var db = require('monk')(url);
var instructors = db.get('instructors');
instructors.insert({
	name: 'Neil Second',
	email: 'fake@driver.com'
});

db.close();
```

Running this file with node results in the record being inserted, but the following error appearing afterwards:

```bash
C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'ops' of null
    at C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\lib\collection.js:310:21
    at C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\lib\util.js:18:12
    at C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\collection.js:503:20
    at C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\collection.js:617:26
    at handleCallback (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\utils.js:96:12)
    at resultHandler (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\bulk\ordered.js:412:11)
    at commandCallback (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:1182:20)
    at Callbacks.flush (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:88:7)
    at Server.destroy (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:1075:41)
    at Server.close (C:\Users\Neil\AppData\Roaming\nvm\v4.4.5\node_modules\monk\node_modules\mongodb\lib\server.js:398:17)                                       
```

Monk version: 2.0.0
Mongo server version: 3 I think
Node version: 4.4.5
Windows version: 10

**Comment by mathieudutour** [comment]
should be fix in monk@2.0.1

**Comment by neil-s** [comment]
Thanks @mathieudutour .  Was this a known issue with a discussion somewhere else? Is there a rough timeline on when the next release is coming, or a workaround until then?

**Comment by mathieudutour** [comment]
it is released already
