### ISSUE TITLE
MongoError: option safe is not supported

### ISSUE THREAD

**Issue by goums** [Automattic/monk#180]
Hi,

A recent update on mongodb nodejs driver has made unknown options undesirable.
Monk seems to be impacted as it gives by default an unsupported option 'safe'  to the driver.

I'm having this error everywhere in the project since this morning:
``` 
debug:mongodb Cannot connect to mongo +6m
debug:mongodb MongoError: option safe is not supported
    at validOptions (/.../node_modules/mongodb/lib/mongo_client.js:50:14)
    at Function.MongoClient.connect (/.../node_modules/mongodb/lib/mongo_client.js:194:13)
    at Manager.open (/.../node_modules/monk/lib/manager.js:129:15)
    at Manager.<anonymous> (/.../node_modules/monk/lib/manager.js:161:14)
    at new Promise (/.../node_modules/core-js/modules/es6.promise.js:191:7)
    at Manager.executeWhenOpened (/.../node_modules/monk/lib/manager.js:159:14)
    at Collection.executeWhenOpened (/.../node_modules/monk/lib/collection.js:75:23)
    at Collection.find (/.../node_modules/monk/lib/collection.js:368:22)
```

Mongo driver team seems to be aware of this regression:
https://jira.mongodb.org/browse/NODE-934
But not sure it will be fixed soon.

Could you remove this option where it is not required?

A quick fix for people having the same problem is to temporarily fix the mongodb driver version to the previous one in your package.json:
`    "mongodb": "2.2.21"`
Then run:
```
> rm -rf node_modules/mongodb/*
> npm install
```

**Comment by mathieudutour** [comment]
Thanks!
