### ISSUE TITLE
db.auth is not a function 

### ISSUE THREAD

**Issue by ChenJiaH** [Automattic/monk#193]
I added a user in the database named uedatabase, but it's not work in nodejs. In command lines, it's can worked.

Code:
```javascript
var monk = require('monk');
var db = monk('10.13.22.105:27017/uedatabase');
db.auth("uedatabase","nDK4om3z7gw0");
```
Error:

TypeError: db.auth is not a function
    at Object.<anonymous> (E:\work\JRMobileGitRepo\jr_teamStation\mobile\routes\api.js:21:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\work\JRMobileGitRepo\jr_teamStation\mobile\app.js:16:11)
    at Module._compile (module.js:570:32)

// Add

By looking at source code, monk connect to the database directly.

```javascript
Manager.prototype.open = function (uri, opts, fn) {
  MongoClient.connect(uri, opts, function (err, db) {
    if (err || !db) {
      this._state = STATE.CLOSED
      this.emit('error-opening', err)
    } else {
      this._state = STATE.OPEN
      this._db = db
      this.emit('open', db)
    }
    if (fn) {
      fn(err, this)
    }
  }.bind(this))
}
```

Is it possible to consider adding 'authenticate'?  

Thanks.

**Comment by ChenJiaH** [comment]
Sorry, It's can be solved by write auth in param 'url' like this:
var db = monk('mongodb://user:pwd@10.13.22.105:27017')
