### ISSUE TITLE
how to fire function on connect

### ISSUE THREAD

**Issue by PinkyRabbit** [Automattic/monk#249]
I tried  to make init config. But when I did such code:
```javascript
const db = monk(config.mdbConnect);
const create = util.promisify(db.create);

db.then(() => create('users'))
  .then(() => create('questions'))
  .then(() => create('events'))
  .then(() => create('settings'))
  .then(() => {
    const main = {
      type: 'main',
      categories: [
        {
          name: 'Peoples',
          creator: 'Someone Somehow',
        },
      ],
    };
    return db.get('settings').insert(main);
  })
  .then(() => db.get('questions').insert(textsToInsert))
  .then(() => {
    debug('Success !');
    db.close();
  })
  .catch(err => debug(err));
```
I got an error:
```
usesa@pinkya-spot:/var/www/haru-bot$ npm run once

> haru-bot@0.0.3 once /var/www/haru-bot
> DEBUG=* node init.js

  monk:manager connection opened +0ms
  monk:manager emptying queries queue (0 to go) +1ms
  Init script TypeError: this.executeWhenOpened is not a function
  Init script     at Manager.create (/var/www/haru-bot/node_modules/monk/lib/manager.js:272:8)
  Init script     at internal/util.js:229:30
  Init script     at db.then (/var/www/haru-bot/init.js:77:15)
  Init script     at <anonymous>
  Init script     at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
```
I read issue stack and know that `executeWhenOpened` is unstable function. But how I can fire my scrip when connection is open? Thanks!

**Comment by PinkyRabbit** [comment]
solved:
```javascript
require('monk')(config.mdbConnect)
  .then((db) => {
    const cr1 = db.create('users');
    const cr2 = db.create('events');
    const main = {
      type: 'main',
      categories: [
        {
          name: 'Люди',
          creator: 'Харухи Судзумия',
        },
      ],
    };
    const ins1 = db.get('settings').insert(main);
    const ins2 = db.get('questions').insert(textsToInsert);

    return Promise.all([cr1, cr2, ins1, ins2]);
  })
  .then(() => {
    debug('Таблицы для данных и настройки успешно созданы. Теперь можете удалить init.js и запускать бота');
    process.exit(0);
  })
  .catch(err => debug(err));
```
But want to say that `executeWhenOpened` in most cases looks more usable. And I found such syntax on dunno where page. So fix this please. Thanks for monk!

**Comment by mathieudutour** [comment]
you can just write

```js
const db = require('monk')(config.mdbConnect)

    const cr1 = db.create('users');
    const cr2 = db.create('events');
    const main = {
      type: 'main',
      categories: [
        {
          name: 'Peoples',
          creator: 'Someone Somehow',
        },
      ],
    };
    const ins1 = db.get('settings').insert(main);
    const ins2 = db.get('questions').insert(textsToInsert);

    Promise.all([cr1, cr2, ins1, ins2])
    .then(() => {
      debug('Success !');
      process.exit(0);
    })
    .catch(err => debug(err));
```
