### ISSUE TITLE
Error: Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by akhileshamar95** [Automattic/monk#286]
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'bcrypt'
Require stack:
- E:\node_crud4\api\routes\user.js
- E:\node_crud4\app.js
- E:\node_crud4\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\node_crud4\api\routes\user.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\node_crud4\app.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\node_crud4\\api\\routes\\user.js',
    'E:\\node_crud4\\app.js',
    'E:\\node_crud4\\server.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by akhileshamar95** [comment]
plz give me a response

**Comment by mathieudutour** [comment]
`bcrypt` isn't used in `monk` so it's an issue in your code, not the library
